### ISSUE TITLE
Ralf doesn't produce any alarms relating to communication with chronos or memcached

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/ralf#119]
When ralf is having trouble communicating with chronos or memcached, it should produce alarms similar to those produced by sprout.

**Comment by mirw** [comment]
@dtheobald, @plfrancis, can one of you pick this up?  You're most familiar with the alarms function.

**Comment by rkd-msw** [comment]
I took a quick look, and there is code in Ralf to do this - https://github.com/Metaswitch/ralf/blob/dev/src/main.cpp#L382.

@dtheobald, do you have debug logs here? It would be good to see if there were any instances of the log at https://github.com/Metaswitch/cpp-common/blob/284634c6e59b87c0f3de13003fc73c4d3ef8b0b9/src/alarm.cpp#L64 (which will tell us whether alarms are being issued from Ralf, but not handled correctly by snmpd) or https://github.com/Metaswitch/ralf/blob/dev/src/main.cpp#L232 (which will show if Ralf is picking up the snmp_ip setting correctly).

**Comment by plfrancis** [comment]
Somehow initialization of the MemcachedStore was moved above the CommunicationMonitor initialization which is intended to be passes as a construction parameter if alarms are enabled. Doug is checking in the fix which moves the CommunicationMonitor construction above the MemcachedStore construction. There was no issue with Ralf issuing Chronos alarms, just Memcached.

**Comment by rkd-msw** [comment]
That was me, in https://github.com/Metaswitch/ralf/commit/8e71cd34d55512288f98d956cad45f534f75d470#diff-7ec3c68a81efff79b6ca22ac1f1eabba - I added code to make Ralf quit if there were no memcached servers, and made the memcached initialization as early as possible as part of that.

It might be worth declaring the CommunicationMonitors and the Alarm right before they're used at https://github.com/Metaswitch/ralf/blob/2bd74f4423e09620a70416440b1383b9644500be/src/main.cpp#L382, instead of declaring them at the top of the function. That would help prevent this sort of issue, and matches our practice elsewhere (e.g. https://github.com/Metaswitch/ralf/blob/2bd74f4423e09620a70416440b1383b9644500be/src/main.cpp#L370).
