### ISSUE TITLE
Ralf performance drop between release-63 and release-73

### ISSUE THREAD

**Issue by plfrancis** [Metaswitch/ralf#155]
Ralf capacity (single instance) measured for release-63 was 105 CPS and 115 CPS for 5 minute and 30 minute registration scenarios respectively (15,000 subscribers). In release-73 these numbers have dropped to 55 CPS and 70 CPS.respectively.

**Comment by mirw** [comment]
The code changes between these revisions are at https://github.com/Metaswitch/ralf/compare/release-63...release-72.

There's nothing obvious here - the only significant change is the introduction of SAS events, but these shouldn't have this significant an effect.

There might also be changes in other repos on which Ralf depends, but these are all in projects that are also common with Homestead, so it seems unlikely.

What's the limiting factor at these loads?  Is it CPU or RAM or is Ralf throttling unnecessary?  Is it the same as it was in release-63?

**Comment by plfrancis** [comment]
The exercise here was to use a fixed number of subscribers and adjust registration interval (for two common scenarios) and call hold time to drive a single Ralf instance to 60% CPU usage. So the limiting factor is the CPU target. Sorry, I have not had a chance to look into possible behavior differences at a system level yet.

**Comment by plfrancis** [comment]
I've compared release-73 with release-63 from a system level perspective with the exact same configuration/environment. Inputs/Outputs are nearly identical for the following scenario: register 2 subs, 1 minute call between subs, deregister 2 subs. There are 32 REST API requests received and 32 ACRs generated. The only difference was that release-73 only needed 46 packets to transfer the REST requests where release 63 used 50 packets.

A 25 CPS traffic run was used to exercise a single Ralf VM (5000 subs, 5 minute registration). For release-73 the CPU reported by top on the Ralf VM was: ralf 28%, chronos 14%, memcached 1%. For release-63 the results were: ralf 16%, chronos 2%, memcached 0.7%.

Profiles were taken during the traffic run with the following results:

release-73 Ralf

![profile_v7_ralf](https://cloud.githubusercontent.com/assets/6798166/8015777/3c9d81d4-0ba1-11e5-8fbb-f02a3bb2044f.png)

release-63 Ralf

![profile_v6_ralf](https://cloud.githubusercontent.com/assets/6798166/8015790/54e5942a-0ba1-11e5-9a78-a6325ba48590.png)

release-73 Chronos

![profile_v7_chronos](https://cloud.githubusercontent.com/assets/6798166/8015796/61357ccc-0ba1-11e5-955c-13ebe53388d5.png)

reelase-63 Chronos

![profile_v6_chronos](https://cloud.githubusercontent.com/assets/6798166/8015799/6a9ff904-0ba1-11e5-9b41-4d4bbe3057aa.png)

**Comment by mirw** [comment]
Thanks!  I'm investigating.

**Comment by mirw** [comment]
OK, so the code changes **in Ralf** between release 63 and release 72 are

*   adding SAS compression (I can see this adds a chunk from the profiler output)
*   changing some of the SAS events (although I don't think this is significant)
*   moving from binary to JSON encoding in the session store.

The profiler output is a bit confusing (I haven't used this one before).  It shows an increase of ~16% in Ralf from compression, but I think this must be a percentage of Ralf's CPU usage rather than a total CPU number.

The changes above are in Ralf, but obviously cpp-common and other dependencies have changed too in the meantime.  I think we should check how much of an effect SAS compression has and see if this accounts for the whole Ralf performance change.  If not, we should probably just bisect the releases to find the other performance change - 9 releases of code changes is quite a lot to look through!

Note that Ralf is likely to be affected by SAS compression more than other components because

*   it deals in bigger messages than most other components
*   it doesn't do as much processing as other components - it generally just passes messages on.

This doesn't cover why Chronos's performance has been affected.  I'm going to raise a new issue to cover that (and pass to @eleanor-merry.

**Comment by mirw** [comment]
I've separated out the Chronos performance issue into https://github.com/Metaswitch/chronos/issues/136.  This issue now only covers specifically the Ralf process performance degration.

**Comment by mirw** [comment]
Please can you test with https://github.com/Metaswitch/sas-client/pull/55?  This won't regain all the performance, but should improve it.

**Comment by plfrancis** [comment]
With SAS compression disabled in the release-73 load, a traffic run with 15,000 subscribers and 30 minute registration is now showing a single Ralf CPU load of 63% at 100 CPS. So, at the 60% target the call rate will probably be around 95-97 CPS. This is down from 115 CPS in release-63, but is far better than the drop to 70 CPS with SAS compression enabled. Closing.
